### PR TITLE
Fix the error when kable()'s caption value is of length > 1

### LINKED ISSUE #2311: kable throws error with HTML caption in R 4.3
Here's an example of a `knitr::kable` call that runs with a warning in R 4.2 and earlier, but fails in R 4.3:

```
knitr::kable(mtcars, caption = htmltools::tags$span('Test Caption', style='color: blue;'), format='html')
Error in !is.null(caption) && !is.na(caption) :
  'length = 3' in coercion to 'logical(1)'
```

```
> xfun::session_info('knitr')
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.7.1

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  evaluate_0.23   graphics_4.3.2  grDevices_4.3.2 highr_0.10
  knitr_1.45.8    methods_4.3.2   stats_4.3.2     tools_4.3.2
  utils_4.3.2     xfun_0.41       yaml_2.3.7
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

### PR DESCRIPTION
**Pull request by LeeMendelowitz**
Fix for #2311.

### CODE REVIEW

File: R/table.R [hunk 1]
```diff
@@ -172,7 +172,10 @@ kable_caption = function(label, caption, format) {
   # create a label for bookdown if applicable
   if (is.null(label)) label = opts_current$get('label')
   if (is.null(label)) label = NA
-  if (!is.null(caption) && !is.na(caption) && !is.na(label)) caption = paste0(
+  is_na = function(v) {
+    length(v) == 0 || (length(v) == 1 && is.na(v))
+  }
+  if (!is.null(caption) && !is_na(caption) && !is_na(label)) caption = paste0(
```
Comment (yihui) [inline R/table.R:178]: No longer need to test for `is.null()` since `is_na(NULL)` is `TRUE`.

```suggestion
  if (!is_na(caption) && !is_na(label)) caption = paste0(
```
